controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    door_controller:
      type: position_controllers/JointGroupPositionController

door_controller:
  ros__parameters:
    joints:
      - right_joint
      - left_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
